---
apiVersion: v1
kind: Secret
metadata:
  name: aaeon-device
  namespace: default
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJteS1jb21wYW55LmNvOjE0NDMiOnsiYXV0aCI6IllXRmxiMjR1WkdWMmFXTmxPbEJpT1UxQlMxZHlNbTVhYTJoNGJnPT0ifX19Cg=="
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: openvino-motion-detector
  name: openvino-motion-detector
  namespace: default
spec:
  hostNetwork: true
  containers:
    - args:
        - python3 app.py 0
      command:
        - /bin/bash
        - -ic
      image: my-company.co:1443/public/opencv-motion-detector:ubuntu20-2021.3
      name: openvino-motion-detector
      env:
        - name: DISPLAY
          value: ":0.0"
      resources: {}
      volumeMounts:
        - mountPath: /tmp/.X11-unix
          name: x11-unix
        - mountPath: /dev/video0
          name: dev-video0
        - mountPath: /dev/dri
          name: dev-dri
      securityContext:
        privileged: true
  imagePullSecrets:
    - name: aaeon-device
  volumes:
    - name: x11-unix
      hostPath:
        path: /tmp/.X11-unix
        type: Directory
    - name: dev-video0
      hostPath:
        path: /dev/video0
        type: CharDevice
    - name: dev-dri
      hostPath:
        path: /dev/dri
        type: Directory
  restartPolicy: OnFailure
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
              - key: aaeon/role
                operator: In
                values:
                  - edge-server
                  - edge-node
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: aaeon/role
                operator: In
                values:
                  - edge-node
  tolerations:
    - key: aaeon/role
      operator: Equal
      value: edge-node
      effect: NoExecute
