---
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-intel-openvino
    image: my-registry/public/opencv-motion-detector:ubuntu20-2021.3
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri
      - /dev/video0
    command: ["/bin/bash", "-ic", "python3 app.py 0"]
