---
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-nvidia-jetson
    image: my-registry/public/opencv-motion-detector:r32.5.0
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0
    command: ["/bin/bash", "-ic", "python3 app.py 0"]
